### ISSUE TITLE
[Badge]: Test

### ISSUE THREAD

**Issue by Holybasil** [scroll-tech/canvas-badges#1]
### Badge Contract Address

0xDcB439703F40430dE360dfeEd51E4261D1fAa310

### Attester Proxy Address

0x83f26d1c451DFCFE2e16B479981c6fA2BCCe053F

### BaseURL of Check/Claim API

https://ambient-scroll-badge.liquidity.tools/api

### Issuer Name

Ambient Finance

**Comment by 0xStrobe** [comment]
hi, this was the deployment before the production contracts from the scroll team were finalized.

the current contracts:

```
  Ambient Swapooor: 0xDaf958ec36dB494e82709a3AaB9FA6981EfC4Dad
  Ambient Providoor: 0xC634b718618729df70331D79fcd6E889a547fbEB
  Ambient Filloor: 0x21C5E85eBCbd924BA633D4A7A5F2718f25C713D8
  Ambient Yeet: 0x7bD1AEADCc59EedaF4775E4D3197Ce9a7031BD01
  
  Attester Proxy: 0xf61B5dAe16948F0f1ed9141634E4647bBaAa4A81
```
