### ISSUE TITLE
[Badge]: Ambient Yeet

### ISSUE THREAD

**Issue by 0xStrobe** [scroll-tech/canvas-badges#10]
### Badge Contract Address

0x7bD1AEADCc59EedaF4775E4D3197Ce9a7031BD01

### Attester Proxy Address

0xf61B5dAe16948F0f1ed9141634E4647bBaAa4A81

### BaseURL of Check/Claim API

https://ambient-scroll-badge.liquidity.tools/api

### Issuer Name

Ambient Finance

### Issuer URL

https://ambient.finance/

**Comment by Holybasil** [comment]
added
