### ISSUE TITLE
TEST

### ISSUE THREAD

**Issue by Ken-Khosa** [scroll-tech/canvas-badges#100]
### Badge Category

Identity

### Badge Contract Address

0x63099fF7Abbb5f2c1ecAfaB4578796Ffb830792F

### Enable isEligible

Yes

### Issuer Name

TEST

**Comment by Ken-Khosa** [comment]
when i parseBadge i got this C:\Users\place\canvas-badges>node scripts/parseBadge.mjs
The contract function "badgeTokenURI" returned no data ("0x").

This could be due to any of the following:
  - The contract does not have the function "badgeTokenURI",
  - The parameters passed to the contract function may be invalid, or
  - The address is not a contract.

Contract Call:
  address:   0x27886BE7f7E5A294d25e62D29d9832778631a0Bc
  function:  badgeTokenURI(bytes32 uid)
  args:                   (0x0000000000000000000000000000000000000000000000000000000000000000)

Docs: https://viem.sh/docs/contract/readContract
Version: viem@2.18.8

Can you guide me about the process. Thanks

**Comment by Holybasil** [comment]
![CleanShot 2024-08-06 at 10 40 31@2x](https://github.com/user-attachments/assets/081f0720-2c49-4e85-a247-5a7ddfa0e500)

**Comment by Holybasil** [comment]
please resubmit a badge form, we require `communityURL` now.
