### ISSUE TITLE
[Badge]: This badge is designed for users who made cross-chain swap from Optimism to Scroll.

### ISSUE THREAD

**Issue by allush** [scroll-tech/canvas-badges#102]
### Badge Category

Achievement

### Badge Contract Address

0x475d1E9Be98B7B7b97D7ED9695541A0209e982dE

### Attester Proxy Address

0x7673F45e6E95373BA22651A4f5f594EDEC3006BC

### BaseURL of Check/Claim API

https://api.symbiosis.finance/crosschain/v1/scroll-badge

### Issuer Name

Symbiosis

### Issuer URL

https://symbiosis.finance/

**Comment by Holybasil** [comment]
added
