### ISSUE TITLE
[Badge]: This badge is designed for users who made cross-chain swap from Taiko to Scroll.

### ISSUE THREAD

**Issue by allush** [scroll-tech/canvas-badges#104]
### Badge Category

Achievement

### Badge Contract Address

0xCA5d53f143822dd8b9789b1A12d2a10A39a499e4

### Attester Proxy Address

0x7673F45e6E95373BA22651A4f5f594EDEC3006BC

### BaseURL of Check/Claim API

https://api.symbiosis.finance/crosschain/v1/scroll-badge

### Issuer Name

Symbiosis

### Issuer URL

https://symbiosis.finance/

**Comment by Holybasil** [comment]
added
