### ISSUE TITLE
[Badge]: This badge is designed for users who made cross-chain swap from zkSync to Scroll.

### ISSUE THREAD

**Issue by allush** [scroll-tech/canvas-badges#106]
### Badge Category

Achievement

### Badge Contract Address

0x9765B7B7926Cb27b84f5F48EA0758Fa99da3C7d6

### Attester Proxy Address

0x7673F45e6E95373BA22651A4f5f594EDEC3006BC

### BaseURL of Check/Claim API

https://api.symbiosis.finance/crosschain/v1/scroll-badge

### Issuer Name

Symbiosis

### Issuer URL

https://symbiosis.finance/

**Comment by Holybasil** [comment]
added
