### ISSUE TITLE
[Badge]: This badge is designed for users who made cross-chain swap from Linea to Scroll.

### ISSUE THREAD

**Issue by allush** [scroll-tech/canvas-badges#108]
### Badge Category

Status

### Badge Contract Address

0x6d352E2987C0AC7D896B74453f400477dE7446F0

### Attester Proxy Address

0x7673F45e6E95373BA22651A4f5f594EDEC3006BC

### BaseURL of Check/Claim API

https://api.symbiosis.finance/crosschain/v1/scroll-badge

### Issuer Name

Symbiosis

### Issuer URL

https://symbiosis.finance/

**Comment by Holybasil** [comment]
added
