### ISSUE TITLE
[Badge]: This badge is designed for users who made cross-chain swap from Mantle to Scroll.

### ISSUE THREAD

**Issue by allush** [scroll-tech/canvas-badges#110]
### Badge Category

Achievement

### Badge Contract Address

0x5bA1cC19C89BeD7d4660316D1eB41B6A581B98c7

### Attester Proxy Address

0x7673F45e6E95373BA22651A4f5f594EDEC3006BC

### BaseURL of Check/Claim API

https://api.symbiosis.finance/crosschain/v1/scroll-badge

### Issuer Name

Symbiosis

### Issuer URL

https://symbiosis.finance/

**Comment by Holybasil** [comment]
added
