### ISSUE TITLE
[Badge]: This badge is designed for users who made cross-chain swap from Polygon zkEVM to Scroll.

### ISSUE THREAD

**Issue by allush** [scroll-tech/canvas-badges#112]
### Badge Category

Status

### Badge Contract Address

0xCd223ce0Cc6C05c1604f8f83A50e98202E600bD6

### Attester Proxy Address

0x7673F45e6E95373BA22651A4f5f594EDEC3006BC

### BaseURL of Check/Claim API

https://api.symbiosis.finance/crosschain/v1/scroll-badge

### Issuer Name

Symbiosis

### Issuer URL

https://symbiosis.finance/

**Comment by Holybasil** [comment]
added
