### ISSUE TITLE
[Badge]: This badge is designed for users who made cross-chain swap from Mode to Scroll.

### ISSUE THREAD

**Issue by allush** [scroll-tech/canvas-badges#114]
### Badge Category

Status

### Badge Contract Address

0x3573335B5128F50F79617f1218f2A7aA0EE68703

### Attester Proxy Address

0x7673F45e6E95373BA22651A4f5f594EDEC3006BC

### BaseURL of Check/Claim API

https://api.symbiosis.finance/crosschain/v1/scroll-badge

### Issuer Name

Symbiosis

### Issuer URL

https://symbiosis.finance/

**Comment by Holybasil** [comment]
added
