### ISSUE TITLE
[Badge]: Zebra Badge

### ISSUE THREAD

**Issue by zebra-xyz** [scroll-tech/canvas-badges#12]
### Badge Contract Address

0x09E14E520eec3583681Fe225a4B506743EC3cc78

### Attester Proxy Address

0x35BcDcd5813a08f890163c166826856B47e7977F

### BaseURL of Check/Claim API

https://zebra.xyz/api/badge

### Issuer Name

Zebra

### Issuer URL

https://app.zebra.xyz/

**Comment by Holybasil** [comment]
added
