### ISSUE TITLE
Nuri Locker Badge

### ISSUE THREAD

**Issue by keccakdog** [scroll-tech/canvas-badges#127]
### Badge Category

Achievement

### Badge Contract Address

0x1dd225EA9585462FF7cb32b1EE7f9a54a4606b66

### Enable isEligible

Yes

### Issuer Name

Nuri Exchange

### Issuer URL

https://nuri.exchange

### Community URL

https://discord.gg/n9wgqpVwsn

**Comment by Holybasil** [comment]
added

**Comment by keccakdog** [comment]
> added
Hey, all tests pass but scroll frontend is throwing an Unauthorized error. @Holybasil any ideas?
![image](https://github.com/user-attachments/assets/c7b98b84-3910-4135-985d-dd3d209d35be)
![image](https://github.com/user-attachments/assets/47e0d4ee-c2f8-4f72-8570-18acb318181f)
https://scroll.io/canvas/badge-contract/0x1dd225EA9585462FF7cb32b1EE7f9a54a4606b66

thanks
