### ISSUE TITLE
[Badge]: Conft 2024 Badge

### ISSUE THREAD

**Issue by Takaiva** [scroll-tech/canvas-badges#139]
### Badge Category

Achievement

### Badge Contract Address

0x218e736Cc77c1339e42Ac6829ae93AC3CEA65b7a

### Enable isEligible

Yes

### Issuer Name

coNFT

### Issuer URL

https://conft.app/

### Community URL

https://x.com/ConftApp

**Comment by Holybasil** [comment]
**Data verification results**
Badge Image: Failed to fetch https://ipfs.io/ipfs/QmeoqEhVD2EygXpM4HTCFBgnRD9cNi5R5uUCFUooNNuYW1

**Comment by Holybasil** [comment]
added
