### ISSUE TITLE
[Badge]: Scrolly's Journey

### ISSUE THREAD

**Issue by ScrollyXYZ** [scroll-tech/canvas-badges#14]
### Badge Contract Address

0x79b4f7492328D0Cc4ED0Ddaee08Cd42f0F36A4CC

### Attester Proxy Address

0x47a49cCfa1924D5b59cb400708199b6Ae8543D31

### BaseURL of Check/Claim API

https://api.scrolly.xyz/api/badge/

### Issuer Name

Scrolly

### Issuer URL

https://hub.scrolly.xyz/

**Comment by Holybasil** [comment]
added
