### ISSUE TITLE
[Badge]: Entry Scroll Bridger Badge

### ISSUE THREAD

**Issue by gemeniteg** [scroll-tech/canvas-badges#147]
### Badge Category

Achievement

### Badge Contract Address

0x75ea8fA878314FDb9325a1652898bEfcccf88292

### Attester Proxy Address

0x850C116ea39b49d8714BE4d1dEffDC1009D66C48

### BaseURL of Check/Claim API

https://owlto.finance/nocore_api/v1/campaign/scroll-badge

### Issuer Name

Owlto Finance

### Community URL

https://discord.gg/owlto

**Comment by Holybasil** [comment]
added
