### ISSUE TITLE
[Badge]: Loyal Scroll Bridger Badge

### ISSUE THREAD

**Issue by gemeniteg** [scroll-tech/canvas-badges#149]
### Badge Category

Achievement

### Badge Contract Address

0x2F942fbCd37693B2f4254fEe6e4cd70508e6235a

### Attester Proxy Address

0x850C116ea39b49d8714BE4d1dEffDC1009D66C48

### BaseURL of Check/Claim API

https://owlto.finance/nocore_api/v1/campaign/scroll-badge

### Issuer Name

Owlto Finance

### Community URL

https://discord.gg/owlto

**Comment by Holybasil** [comment]
added
