### ISSUE TITLE
[Badge]: Fanaticism Scroll Bridger Badge

### ISSUE THREAD

**Issue by gemeniteg** [scroll-tech/canvas-badges#151]
### Badge Category

Achievement

### Badge Contract Address

0xB9CD7EC2A2261AEA5B0251cf2394e5345C95df61

### Attester Proxy Address

0x850C116ea39b49d8714BE4d1dEffDC1009D66C48

### BaseURL of Check/Claim API

https://owlto.finance/nocore_api/v1/campaign/scroll-badge

### Issuer Name

Owlto Finance

### Community URL

https://discord.gg/owlto

**Comment by Holybasil** [comment]
added
