### ISSUE TITLE
[Badge]: Toaster GM Badge

### ISSUE THREAD

**Issue by swimmiee** [scroll-tech/canvas-badges#156]
### Badge Category

Achievement

### Badge Contract Address

0xFb070831e0Acf47c90C3c91fdF11b0c99FaD1e17

### Attester Proxy Address

0xCF27c9bCCCEA79215CB4c48a29ABb485CA060fE8

### BaseURL of Check/Claim API

https://api.toaster.finance/api/external/scrol-badge

### Issuer Name

Toaster Finance

### Community URL

https://t.me/+Mv-_ZMfm2ssxODUx

**Comment by Holybasil** [comment]
Check API: Unable to access https://api.toaster.finance/api/external/scrol-badge/check?badge=0xFb070831e0Acf47c90C3c91fdF11b0c99FaD1e17&recipient=0xe4657139e50E909731de703E1728128197a90447 on Scroll.io. Please configure cross-origin resource sharing (CORS).

**Comment by swimmiee** [comment]
@Holybasil fixed CORS issue

**Comment by swimmiee** [comment]
Fixed typo at **BaseURL of Check/Claim API**
`From` https://api.toaster.finance/api/external/scrol-badge
`To` https://api.toaster.finance/api/external/scroll-badge
