### ISSUE TITLE
Panda Canvas Badge 

### ISSUE THREAD

**Issue by buildforest** [scroll-tech/canvas-badges#16]
### Badge Contract Address

0x17D86f3dc041352383E68f459310d7f7cCF47105

### Attester Proxy Address

0xa68a32Ead85B45044bCD2B2D8c1C7Fe190D5De2D

### BaseURL of Check/Claim API

no

### Issuer Name

Panda

### Issuer URL

pandacoin.sc

**Comment by Holybasil** [comment]
please resubmit a badge form, we require `communityURL` now.
