### ISSUE TITLE
[Badge]: Toaster OG Badge

### ISSUE THREAD

**Issue by swimmiee** [scroll-tech/canvas-badges#160]
### Badge Category

Status

### Badge Contract Address

0xE110648a9563940964D7840f469403AaDC714871

### Attester Proxy Address

0xCF27c9bCCCEA79215CB4c48a29ABb485CA060fE8

### BaseURL of Check/Claim API

https://api.toaster.finance/api/external/scrol-badge

### Issuer Name

Toaster Finance

### Community URL

https://t.me/+Mv-_ZMfm2ssxODUx

**Comment by Holybasil** [comment]
Check API: Unable to access https://api.toaster.finance/api/external/scrol-badge/check?badge=0xE110648a9563940964D7840f469403AaDC714871&recipient=0xe4657139e50E909731de703E1728128197a90447 on Scroll.io. Please configure cross-origin resource sharing (CORS).

**Comment by swimmiee** [comment]
@Holybasil fixed CORS issue

**Comment by swimmiee** [comment]
Fixed typo at **BaseURL of Check/Claim API**
`From` https://api.toaster.finance/api/external/scrol-badge
`To` https://api.toaster.finance/api/external/scroll-badge

**Comment by swimmiee** [comment]
@Holybasil do we need to open a new issue?

**Comment by Holybasil** [comment]
> @Holybasil do we need to open a new issue?

No, we have received 4 badges from Toaster Finance. They will be listed on the Canvas and Badges page once we complete the review

**Comment by swimmiee** [comment]
> > @Holybasil do we need to open a new issue?
> 
> No, we have received 4 badges from Toaster Finance. They will be listed on the Canvas and Badges page once we complete the review

Thanks. May I ask how long it will take to be reviewed?
