### ISSUE TITLE
[Badge]: Venister Badge

### ISSUE THREAD

**Issue by ic3IT** [scroll-tech/canvas-badges#164]
### Badge Category

Identity

### Badge Contract Address

0x8483Ae3b737173b9f56d91D64999479274216ffF

### Enable isEligible

Yes

### Issuer Name

Venium

### Issuer URL

https://www.venverse.venium.io/badges

### Community URL

https://discord.gg/venium

**Comment by Holybasil** [comment]
enter the review stage
