### ISSUE TITLE
[Badge]: Intact Persona Badge

### ISSUE THREAD

**Issue by SD17-INT** [scroll-tech/canvas-badges#167]
### Badge Category

Achievement

### Badge Contract Address

0x56c607f29dc1ec34cf66d608925643bad7282a71

### Attester Proxy Address

0x856fc48cabf7f3021d21fe21a1703cb2d69163b0

### BaseURL of Check/Claim API

https://publicapi.intract.io/api/pv1/external/scroll-badges

### Issuer Name

Intract

### Issuer URL

https://www.intract.io/

### Community URL

https://discord.com/invite/faXj8Yzua6/

**Comment by Holybasil** [comment]
**Data verification results**
**Attester Check**: 0x856fc48cabf7f3021d21fe21a1703cb2d69163b0 should be an attester of 0x56c607f29dc1ec34cf66d608925643bad7282a71
**Check API**: Unable to access https://publicapi.intract.io/api/pv1/external/scroll-badges/check?badge=0x56c607f29dc1ec34cf66d608925643bad7282a71&recipient=0xe4657139e50E909731de703E1728128197a90447 on Scroll.io. Please configure cross-origin resource sharing (CORS).



Once you're done with the modifications, please feel free to submit your badge through https://scroll.io/canvas/listing. Thanks!
