### ISSUE TITLE
[Badge]: Passport Unique Humanity Score

### ISSUE THREAD

**Issue by lucianHymer** [scroll-tech/canvas-badges#17]
### Badge Contract Address

0xa623f348A12cFdC6B64a8c9e883dD9B243438E79

### Attester Proxy Address

0x39571bBD5a4c5d1a5184004c63F45FE426dB85Ea

### BaseURL of Check/Claim API

https://passport-iam.gitcoin.co/scroll

### Issuer Name

Passport XYZ

### Issuer URL

https://passport.gitcoin.co/#/scroll

**Comment by Holybasil** [comment]
added
