### ISSUE TITLE
[Badge]: This badge is designed for users holding Hippo Realm NFTs on Scroll.

### ISSUE THREAD

**Issue by duongnd** [scroll-tech/canvas-badges#171]
### Badge Category

Achievement

### Badge Contract Address

0x5C99a6298BBdA89FCF4398FDDd1997e455c6f155

### Attester Proxy Address

0x825fa355BB4FFb7e385c8c4f556f1aDf9897211C

### BaseURL of Check/Claim API

https://api.hipposwap.finance/api/badge/holder

### Issuer Name

Hippo Swap

### Issuer URL

https://hipposwap.finance/

### Community URL

https://link3.to/hipposwap

**Comment by Holybasil** [comment]
enter the review stage
