### ISSUE TITLE
[Badge]: This badge is designed for users who holding Scroll NFTs on RubyScore

### ISSUE THREAD

**Issue by rubyscore-tech** [scroll-tech/canvas-badges#174]
### Badge Category

Status

### Badge Contract Address

0x97e02Bc54a98f48B7858357030dAb2f22f701c3B

### Attester Proxy Address

0x3d52d95D58fCb53814ea37d580601D2AF2B4CC98

### BaseURL of Check/Claim API

https://rubyscore.io/api/scroll-badge

### Issuer Name

RubyScore

### Issuer URL

https://rubyscore.io/dashboard?net=scroll

### Community URL

https://discord.gg/rubyscore

**Comment by Holybasil** [comment]
**Data verification results**
**Attester Check**: 0x3d52d95D58fCb53814ea37d580601D2AF2B4CC98 should be an attester of 0x97e02Bc54a98f48B7858357030dAb2f22f701c3B
**Check API**: Unable to access https://rubyscore.io/api/scroll-badge/check?badge=0x97e02Bc54a98f48B7858357030dAb2f22f701c3B&recipient=0xe4657139e50E909731de703E1728128197a90447 on Scroll.io. Please configure cross-origin resource sharing (CORS).

Once you're done with the modifications, please feel free to submit your badge through https://scroll.io/canvas/listing. Thanks!
