### ISSUE TITLE
[Badge]: Explorer Certificate（Added, but need to update metadata）

### ISSUE THREAD

**Issue by LaplaceMan** [scroll-tech/canvas-badges#176]
### Badge Category

Achievement

### Badge Contract Address

0x4e2F089a2919df2f0264Fd5e8B43b794F3098808

### Attester Proxy Address

0x764Af55daf1cBC7049FAef8e6BC3F626534a7D74

### BaseURL of Check/Claim API

https://publicapi.xenobunny.xyz/canvas/certificate

### Issuer Name

XenoBunny

### Issuer URL

https://www.xenobunny.xyz/

### Community URL

https://discord.gg/9RHJ2PTs

**Comment by LaplaceMan** [comment]
This badge has been added, but need help updating the badge metadata returned by `defaultTokenURI`, thanks!

**Comment by Holybasil** [comment]
will update later
