### ISSUE TITLE
[Badge]: 

### ISSUE THREAD

**Issue by 0xOddrey** [scroll-tech/canvas-badges#18]
### Badge Contract Address

0xBbA25F2539af23E7405E58F935de388A627120c6

### Attester Proxy Address

0x492815d7C37c5310C86A7E66De20d6A1Ca361990

### BaseURL of Check/Claim API

https://vwb06c8e7h.execute-api.us-east-1.amazonaws.com/dev/

### Issuer Name

Scroller NFT

### Issuer URL

https://www.scrollernft.xyz

**Comment by Holybasil** [comment]
added
