### ISSUE TITLE
[Badge]: OmniHub Gold Badge

### ISSUE THREAD

**Issue by omnihub-xyz** [scroll-tech/canvas-badges#189]
### Badge Category

Status

### Badge Contract Address

0x553aF61373B694B7d28CbcF76cF61BE53f323Cc1

### Attester Proxy Address

0x94a4eFD397a035fFD6174445C9d5Ff3AcF9301e9

### BaseURL of Check/Claim API

https://scroll-api-v2.vercel.app/api

### Issuer Name

OmniHub

### Issuer URL

https://omnihub.xyz

### Community URL

https://discord.gg/w5ShHyTvhy

**Comment by Holybasil** [comment]
**Data verification results**
**Check API**: Unable to access https://scroll-api-v2.vercel.app/api/check?badge=0x553aF61373B694B7d28CbcF76cF61BE53f323Cc1&recipient=0xe4657139e50E909731de703E1728128197a90447 on Scroll.io. Please configure cross-origin resource sharing (CORS).

Once you're done with the modifications, please feel free to submit your badge through https://scroll.io/canvas/listing. Thanks!
