### ISSUE TITLE
[Badge]: OmniHub Guardian Badge

### ISSUE THREAD

**Issue by omnihub-xyz** [scroll-tech/canvas-badges#190]
### Badge Category

Status

### Badge Contract Address

0xE7f10EC881D3bdEF9a67F4c6A5070FfD9A4f7FeE

### Attester Proxy Address

0x8499a8bd1051eD3011CB79295d7286d5c9Fe8aF9

### BaseURL of Check/Claim API

https://scroll-api-v2.vercel.app/api

### Issuer Name

OmniHub

### Issuer URL

https://omnihub.xyz/collection/scroll/scroll-guardian

### Community URL

https://discord.gg/w5ShHyTvhy

**Comment by Holybasil** [comment]
**Data verification results**
**Check API**: Unable to access https://scroll-api-v2.vercel.app/api/check?badge=0xE7f10EC881D3bdEF9a67F4c6A5070FfD9A4f7FeE&recipient=0xe4657139e50E909731de703E1728128197a90447 on Scroll.io. Please configure cross-origin resource sharing (CORS).

Once you're done with the modifications, please feel free to submit your badge through https://scroll.io/canvas/listing. Thanks!
