### ISSUE TITLE
[Badge]: Landing on Scroll

### ISSUE THREAD

**Issue by LaplaceMan** [scroll-tech/canvas-badges#205]
### Badge Category

Achievement

### Badge Contract Address

0xC8AedaFcAa7957Ba5A0d2dFeCA0d1eaa397afb2d

### Attester Proxy Address

0xcF136b24EAfd35623d257FE9CF872799bBfec299

### BaseURL of Check/Claim API

https://publicapi.xenobunny.xyz/canvas/landing

### Issuer Name

XenoBunny

### Issuer URL

https://www.xenobunny.xyz/

### Community URL

https://discord.gg/9RHJ2PTs

**Comment by Holybasil** [comment]
enter the review stage
