### ISSUE TITLE
[Badge]: Senior Scroll Explorer

### ISSUE THREAD

**Issue by LaplaceMan** [scroll-tech/canvas-badges#207]
### Badge Category

Achievement

### Badge Contract Address

0xe5B9151F1d995DCF33F63F0f982789A10F87D47e

### Attester Proxy Address

0xFA9729Dee92cD868603B8960A3e6234B2B5A4206

### BaseURL of Check/Claim API

https://publicapi.xenobunny.xyz/canvas/lands/senior

### Issuer Name

XenoBunny

### Issuer URL

https://www.xenobunny.xyz/

### Community URL

https://discord.gg/9RHJ2PTs

**Comment by Holybasil** [comment]
enter the review stage
