### ISSUE TITLE
[Badge]: SmileCobra GL Badge

### ISSUE THREAD

**Issue by smilecobra** [scroll-tech/canvas-badges#209]
### Badge Category

Achievement

### Badge Contract Address

0x980f717C3D76faAfEe3382424F83C5e11f045029

### Attester Proxy Address

0xA6447fA0508c6bEfb413a0adE5fCfe26C4998DeA

### BaseURL of Check/Claim API

https://api.smilecobra.io/tripartite/scroll/badge

### Issuer Name

SmileCobra Studio

### Issuer URL

https://www.smilecobra.io/puzzle

### Community URL

https://www.smilecobra.io/puzzle

**Comment by Holybasil** [comment]
enter the review stage
