### ISSUE TITLE
[Badge]: Pencil S Badge

### ISSUE THREAD

**Issue by penpad-dev** [scroll-tech/canvas-badges#21]
### Badge Contract Address

0x766e3f1EE86439DE0597F6e917F980A4e5d187A3

### Attester Proxy Address

0x43B643299110F99536aBE0ACA64c98BeD7360286

### BaseURL of Check/Claim API

https://pencilsprotocol.io/api/scroll/canvas/badge/pencil

### Issuer Name

Pencils Protocol

### Issuer URL

https://pencilsprotocol.io

**Comment by Holybasil** [comment]
added
