### ISSUE TITLE
[Badge]: FLock Contribution Scroll Badge

### ISSUE THREAD

**Issue by MIDAV0** [scroll-tech/canvas-badges#211]
### Badge Category

Achievement

### Badge Contract Address

0xcde4CaeCcDdfE488f3658172B068b2E748501281

### Attester Proxy Address

0x95Bb879Ff04c76BC5d97097aD90465e8CA129480

### BaseURL of Check/Claim API

https://beta.flock.io/api/scrollNFT

### Issuer Name

FLock.io

### Issuer URL

https://www.flock.io/

### Community URL

https://discord.gg/nq2QBX5K

**Comment by Holybasil** [comment]
**Data verification results**
**DefaultTokenURI**: name is empty
**Issuer Name**: Failed to fetch issuer detail, please try again
**Check API**: Unable to access https://beta.flock.io/api/scrollNFT/check?badge=0xcde4CaeCcDdfE488f3658172B068b2E748501281&recipient=0xe4657139e50E909731de703E1728128197a90447 on Scroll.io. Please configure cross-origin resource sharing (CORS).

Once you're done with the modifications, please feel free to submit your badge through https://scroll.io/canvas/listing. Thanks!
