### ISSUE TITLE
[Badge]: FLock Chat Scroll Badge

### ISSUE THREAD

**Issue by MIDAV0** [scroll-tech/canvas-badges#212]
### Badge Category

Achievement

### Badge Contract Address

0x1755C30672E3EcBB9E8d76051C7a3e1072c53172

### Attester Proxy Address

0xF2a44CCf79FD3F2e46e158Aab9b5726230a3Afd7

### BaseURL of Check/Claim API

https://beta.flock.io/api/scrollNFT

### Issuer Name

FLock.io

### Issuer URL

https://www.flock.io/

### Community URL

https://discord.gg/nq2QBX5K

**Comment by Holybasil** [comment]
**Data verification results**
**DefaultTokenURI**: name is empty
**Issuer Name**: Failed to fetch issuer detail, please try again
**Check API**: Unable to access https://beta.flock.io/api/scrollNFT/check?badge=0x1755C30672E3EcBB9E8d76051C7a3e1072c53172&recipient=0xe4657139e50E909731de703E1728128197a90447 on Scroll.io. Please configure cross-origin resource sharing (CORS).

Once you're done with the modifications, please feel free to submit your badge through https://scroll.io/canvas/listing. Thanks!
