### ISSUE TITLE
[Badge]: MiniBridge Bronze Badge

### ISSUE THREAD

**Issue by Hylance** [scroll-tech/canvas-badges#215]
### Badge Category

Achievement

### Badge Contract Address

0xDf219e18e978E334413dBa943A0c4c32539FD487

### Attester Proxy Address

0x6a2b88275dE6BFF1992fb25371DfC0073349B22b

### BaseURL of Check/Claim API

https://op.chaineye.tools/minibridge/scroll

### Issuer Name

Mini Bridge

### Issuer URL

https://minibridge.chaineye.tools/?dst=scroll

### Community URL

https://t.me/chaineye

**Comment by Holybasil** [comment]
**Data verification results**
**Check API**: Failed to fetch https://op.chaineye.tools/minibridge/scroll/check?badge=0xDf219e18e978E334413dBa943A0c4c32539FD487&recipient=0xe4657139e50E909731de703E1728128197a90447

Once you're done with the modifications, please feel free to submit your badge through https://scroll.io/canvas/listing. Thanks!
