### ISSUE TITLE
[Badge]: Conft Scroll Box

### ISSUE THREAD

**Issue by Takaiva** [scroll-tech/canvas-badges#218]
### Badge Category

Achievement

### Badge Contract Address

0x450Efa43661F5D669c35Ed62e18Bed4D6E826508

### Enable isEligible

Yes

### Issuer Name

coNFT

### Issuer URL

https://conft.app/scroll/collections/0xcf7f37b4916ac5c530c863f8c8bb26ec1e8d2ccb/nft

### Community URL

https://x.com/ConftApp

**Comment by Holybasil** [comment]
![CleanShot 2024-08-16 at 14 36 23@2x](https://github.com/user-attachments/assets/6c6bbaaa-332a-47fd-b412-1833fab644e7)
badge image can't appear

Once you're done with the modifications, please feel free to submit your badge through https://scroll.io/canvas/listing. Thanks!
