### ISSUE TITLE
[Badge]: Pencil P Badge

### ISSUE THREAD

**Issue by penpad-dev** [scroll-tech/canvas-badges#23]
### Badge Contract Address

0x2d8E67c1427a1ebb9ddB5c4D38143140B0c19aC8

### Attester Proxy Address

0xe657243DF50dbC60383f9504bE22f7288174095c

### BaseURL of Check/Claim API

https://pencilsprotocol.io/api/scroll/canvas/badge/pencil

### Issuer Name

Pencils Protocol

### Issuer URL

https://pencilsprotocol.io

**Comment by Holybasil** [comment]
added
