### ISSUE TITLE
[Badge]: FLock Chat Scroll Badge

### ISSUE THREAD

**Issue by ryonzhang** [scroll-tech/canvas-badges#25]
### Badge Contract Address

0xC621B8B9D77B795F2E485FDc14B997AF4d93f226

### Attester Proxy Address

0xF2a44CCf79FD3F2e46e158Aab9b5726230a3Afd7

### BaseURL of Check/Claim API

https://beta.flock.io/api/scrollNFT

### Issuer Name

Flock.io

### Issuer URL

https://www.flock.io/

**Comment by Holybasil** [comment]
please resubmit a badge form, we require `communityURL` now.
