### ISSUE TITLE
[Badge]: FLock Contribution Scroll Badge

### ISSUE THREAD

**Issue by ryonzhang** [scroll-tech/canvas-badges#26]
### Badge Contract Address

0x51cbC7bC00020512E9EF2682bf1215224aC50242

### Attester Proxy Address

0x95Bb879Ff04c76BC5d97097aD90465e8CA129480

### BaseURL of Check/Claim API

https://beta.flock.io/api/scrollNFT

### Issuer Name

Flock.io

### Issuer URL

https://www.flock.io/

**Comment by Holybasil** [comment]
please resubmit a badge form, we require `communityURL` now.
