### ISSUE TITLE
[Badge]: Scroller NFT UPDATED

### ISSUE THREAD

**Issue by 0xOddrey** [scroll-tech/canvas-badges#27]
### Badge Contract Address

0xBbA25F2539af23E7405E58F935de388A627120c6

### Attester Proxy Address

0x045f9B1089F08C84045017B46dea9f72dEF36bb6

### BaseURL of Check/Claim API

https://vwb06c8e7h.execute-api.us-east-1.amazonaws.com/dev/

### Issuer Name

Scroller NFT

### Issuer URL

https://www.scrollernft.xyz

**Comment by Holybasil** [comment]
added
