### ISSUE TITLE
[Badge]: Ambient Swapooor

### ISSUE THREAD

**Issue by 0xStrobe** [scroll-tech/canvas-badges#4]
### Badge Contract Address

0xDaf958ec36dB494e82709a3AaB9FA6981EfC4Dad

### Attester Proxy Address

0xf61B5dAe16948F0f1ed9141634E4647bBaAa4A81

### BaseURL of Check/Claim API

https://ambient-scroll-badge.liquidity.tools/api

### Issuer Name

Ambient Finance

### Issuer URL

https://ambient.finance/

**Comment by Holybasil** [comment]
added
