### ISSUE TITLE
[Badge]: Symbiosis Cross-chain Professional

### ISSUE THREAD

**Issue by allush** [scroll-tech/canvas-badges#40]
### Badge Contract Address

0x847a12d159E1380a06e0Cf9978bc61798387a482

### Attester Proxy Address

0x6EC031F48CE8AB780E2954fDCCFc93FFe9fc1353

### BaseURL of Check/Claim API

https://api.symbiosis.finance/crosschain/v1/scroll-badge

### Issuer Name

Symbiosis

### Issuer URL

https://symbiosis.finance

**Comment by Holybasil** [comment]
added
