### ISSUE TITLE
[Badge]: Trusta Reputation Attestation

### ISSUE THREAD

**Issue by LeilaBlack** [scroll-tech/canvas-badges#43]
### Badge Contract Address

0x47FF789Da49686C6cC38998F76F78A12A5939082

### Attester Proxy Address

0x65AB4b5f30AeF8B29858eA2cbD6b0d0E68010206

### BaseURL of Check/Claim API

https://mp.trustalabs.ai/attestations/media_badge/

### Issuer Name

Trusta Labs

### Issuer URL

https://trustgo.trustalabs.ai/att/scm

**Comment by Holybasil** [comment]
Unable to find the relevant data in the ecosystem list.

please ensure the `Issuer Name` is as same as the one listed on [Scroll Ecosystem](https://scroll.io/ecosystem#protocols).

**Comment by LeilaBlack** [comment]
Edited the issuer name, kindly check again, thanks! @Holybasil

**Comment by Holybasil** [comment]
added
