### ISSUE TITLE
[Badge]: Scroll Cross-chain Professional

### ISSUE THREAD

**Issue by allush** [scroll-tech/canvas-badges#44]
### Badge Contract Address

0xB936740f00FFA90a55C362C33840913eaCFDcE25

### Attester Proxy Address

0x7673F45e6E95373BA22651A4f5f594EDEC3006BC

### BaseURL of Check/Claim API

https://api.symbiosis.finance/crosschain/v1/scroll-badge

### Issuer Name

Symbiosis

### Issuer URL

https://symbiosis.finance

**Comment by allush** [comment]
Could you replace previous badge please? It has an issue (EAS and AttesterProxy versions mismatch)

**Comment by Holybasil** [comment]
updated
