### ISSUE TITLE
[Badge]: Scroll Cross-chain Whale

### ISSUE THREAD

**Issue by allush** [scroll-tech/canvas-badges#47]
### Badge Contract Address

0xaE98FC0e46977DaF650B180041dB20155ac66277

### Attester Proxy Address

0x7673F45e6E95373BA22651A4f5f594EDEC3006BC

### BaseURL of Check/Claim API

https://api.symbiosis.finance/crosschain/v1/scroll-badge

### Issuer Name

Symbiosis

### Issuer URL

https://symbiosis.finance

**Comment by Holybasil** [comment]
added
