### ISSUE TITLE
[Badge]: Scroll Swapper

### ISSUE THREAD

**Issue by allush** [scroll-tech/canvas-badges#49]
### Badge Contract Address

0x3c1A82D5877AB970Be9d80AB8185C5F9F1505C49

### Attester Proxy Address

0x7673F45e6E95373BA22651A4f5f594EDEC3006BC

### BaseURL of Check/Claim API

https://api.symbiosis.finance/crosschain/v1/scroll-badge

### Issuer Name

Symbiosis

### Issuer URL

https://symbiosis.finance

**Comment by Holybasil** [comment]
added
