### ISSUE TITLE
[Badge]: Scroll cross-chain Beginner

### ISSUE THREAD

**Issue by allush** [scroll-tech/canvas-badges#51]
### Badge Contract Address

0x66703cd7eBA1b114cA652b1C2DE268858cBedEc8

### Attester Proxy Address

0x7673F45e6E95373BA22651A4f5f594EDEC3006BC

### BaseURL of Check/Claim API

https://api.symbiosis.finance/crosschain/v1/scroll-badge

### Issuer Name

Symbiosis

### Issuer URL

https://symbiosis.finance

**Comment by Holybasil** [comment]
added
