### ISSUE TITLE
[Badge]: XSTAR XHS Badge

### ISSUE THREAD

**Issue by zerokarafont** [scroll-tech/canvas-badges#53]
### Badge Contract Address

0x7C0deB6aBf29cC829186933720af67da8B1EF633

### Attester Proxy Address

0xc2968d15a98406582a9fbc40c4508ce9cad4577e

### BaseURL of Check/Claim API

https://scroll-canvas-api.xname.app/api/check

### Issuer Name

XSTAR

**Comment by Holybasil** [comment]
pls confirm: your `BaseURL of Check/Claim API` is https://scroll-canvas-api.xname.app/api/check or https://scroll-canvas-api.xname.app/api ?

**Comment by zerokarafont** [comment]
sorry, it is https://scroll-canvas-api.xname.app/api

**Comment by Holybasil** [comment]
added
