### ISSUE TITLE
[Badge]: XSTAR Booster Badge

### ISSUE THREAD

**Issue by zerokarafont** [scroll-tech/canvas-badges#55]
### Badge Contract Address

0xed269A526ad793CcB671Ef55A7AF6E45F300d462

### Attester Proxy Address

0xA599bA9656CD5bb3C1D841c9866704BdEB724DFe

### BaseURL of Check/Claim API

https://scroll-canvas-api.xname.app/api/domain

### Issuer Name

XSTAR

**Comment by Holybasil** [comment]
added
