### ISSUE TITLE
[Badge]: OmniHub Badge

### ISSUE THREAD

**Issue by omnihub-xyz** [scroll-tech/canvas-badges#57]
### Badge Contract Address

0xdd8CCDad022999afD61DFda146e4C40F47dE4Eec

### Attester Proxy Address

0x13babb8C705506Fd71f7e9Aff431B9aF2E659FE9

### BaseURL of Check/Claim API

https://api.omnihub.xyz/api/integration/scroll

### Issuer Name

OmniHub

### Issuer URL

https://omnihub.xyz

**Comment by Holybasil** [comment]
added
