### ISSUE TITLE
[Badge]: Ambient Providoor

### ISSUE THREAD

**Issue by 0xStrobe** [scroll-tech/canvas-badges#6]
### Badge Contract Address

0xC634b718618729df70331D79fcd6E889a547fbEB

### Attester Proxy Address

0xf61B5dAe16948F0f1ed9141634E4647bBaAa4A81

### BaseURL of Check/Claim API

https://ambient-scroll-badge.liquidity.tools/api

### Issuer Name

Ambient Finance

### Issuer URL

https://ambient.finance/

**Comment by Holybasil** [comment]
added
