### ISSUE TITLE
[Badge]: Proof of Humanity Badge

### ISSUE THREAD

**Issue by LeilaBlack** [scroll-tech/canvas-badges#60]
### Badge Category

Identity

### Badge Contract Address

0x26B97C832C04C06cAd34dCE23c701beDC3555a5c

### Attester Proxy Address

0x9C8a1c5B993BaF52E9dD920181767b67bBd4d3A6

### BaseURL of Check/Claim API

https://mp.trustalabs.ai/attestations/poh_badge/

### Issuer Name

Trusta Labs

### Issuer URL

https://trustgo.trustalabs.ai/att/scs

**Comment by Holybasil** [comment]
added
