### ISSUE TITLE
[Badge]: Scroll RetroBridger

### ISSUE THREAD

**Issue by fthoctober** [scroll-tech/canvas-badges#61]
### Badge Category

Achievement

### Badge Contract Address

0x59700c6Ed282eD7611943129f226914ACBB3982b

### Attester Proxy Address

0xbE3B5EB273567D3D5CeAB69815CfD254Ee48FAF3

### BaseURL of Check/Claim API

https://backend.retrobridge.io/api/quest

### Issuer Name

Retro Bridge

### Issuer URL

https://app.retrobridge.io

**Comment by Holybasil** [comment]
got 
![CleanShot 2024-07-31 at 09 23 03@2x](https://github.com/user-attachments/assets/0f7b5b69-9963-4305-a616-c4de5b785a4f)

pls refer to 
![CleanShot 2024-07-31 at 09 20 56@2x](https://github.com/user-attachments/assets/482135de-c84b-442f-bf94-e9a31c5f8454)

**Comment by fthoctober** [comment]
@Holybasil  Made changes in contract, check pls

**Comment by Holybasil** [comment]
added

**Comment by fthoctober** [comment]
@Holybasil Hey
Our users are facing problems with mint
For our part, we looked through everything and everything is fine
Isn't the problem on your side and have you looked at our contracts?

**Comment by finzman** [comment]
It would be great if we could resolve this issue as soon as possible, as the community is concerned about their inability to mint badges.

Thanks in advance @Holybasil

**Comment by Holybasil** [comment]
Below are the parameters I parsed from the user's tx data for the `attestByDelegation` call and the data source is from [this](https://backend.retrobridge.io/api/quest/claim?badge=0x59700c6Ed282eD7611943129f226914ACBB3982b&recipient=0xAbA6528C72Dd675F2Cd42d97458F380A386408B8)

```
[
  [
    '0xd0b86852e21f9e5fa4bc3b0cff9757ffe243d50c4b43968a42202153d651ea5e', // this should be as same as SCROLL_MAINNET_BADGE_SCHEMA
    Result(6) [
      '0xAbA6528C72Dd675F2Cd42d97458F380A386408B8',
      0n,
      true,
      '0x0000000000000000000000000000000000000000000000000000000000000000',
      '0x00000000000000000000000059700c6ed282ed7611943129f226914acbb3982b00000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000',
      0n
    ],
    [
      27n,
      '0x5d1d50e58c1799b61e92a8b2042b7ed4fadc2fca4fcbe24fe83275e01b0d8ea2',
      '0x5bc97713b7fd565e76857f4f58c345c203546fa2a062435ea51e5b89a87578b0'
    ],
    '0x009905bf008CcA637185EEaFE8F51BB56dD2ACa7', // the address is not an attester of the  Attester Proxy Address
    1722514226n
  ]
]
```

pls ensure you have used the correct value in https://github.com/scroll-tech/canvas-contracts/blob/master/docs/deployments.md

**Comment by finzman** [comment]
Seems the issue is resolved now, thanks a lot for prompt help @Holybasil
