### ISSUE TITLE
[Badge]: Conft 2024 Badge

### ISSUE THREAD

**Issue by Takaiva** [scroll-tech/canvas-badges#62]
### Badge Category

Achievement

### Badge Contract Address

0x218e736Cc77c1339e42Ac6829ae93AC3CEA65b7a

### Enable isEligible

Yes

### Issuer Name

coNFT

### Issuer URL

https://conft.app/

**Comment by Holybasil** [comment]
Unable to find the relevant data in the ecosystem list
Issue Name should be as same as the one listed on Scroll Ecosystem.

**Comment by Takaiva** [comment]
> Unable to find the relevant data in the ecosystem list Issue Name should be as same as the one listed on Scroll Ecosystem.

Yeah, sorry, we applied for the ecosystem list yesterday. I believe it is being reviewed now

**Comment by Takaiva** [comment]
@Holybasil We are now in the ecosystem page, can we proceed please?

**Comment by Holybasil** [comment]
Badge Image: Failed to fetch https://ipfs.io/ipfs/QmeoqEhVD2EygXpM4HTCFBgnRD9cNi5R5uUCFUooNNuYW1

**Comment by Holybasil** [comment]
please resubmit a badge form, we require `communityURL` now.
