### ISSUE TITLE
[Badge]: Symbiosis Pro Swapper

### ISSUE THREAD

**Issue by allush** [scroll-tech/canvas-badges#65]
### Badge Category

Achievement

### Badge Contract Address

0x0a584c042133aF17f3e522F09A77Ee1496f3a567

### Attester Proxy Address

0x7673F45e6E95373BA22651A4f5f594EDEC3006BC

### BaseURL of Check/Claim API

https://api.symbiosis.finance/crosschain/v1/scroll-badge

### Issuer Name

Symbiosis

### Issuer URL

https://symbiosis.finance/

**Comment by Holybasil** [comment]
added
