### ISSUE TITLE
[Badge]: Scroll Overlord Badge

### ISSUE THREAD

**Issue by LaplaceMan** [scroll-tech/canvas-badges#66]
### Badge Category

Achievement

### Badge Contract Address

0xb2c69173829E23EE2876FBe13Ab474FEe101bc64

### Enable isEligible

Yes

### Issuer Name

XenoBunny

### Issuer URL

https://www.xenobunny.xyz/

**Comment by Holybasil** [comment]
Unable to find the relevant data in the ecosystem list

Please ensure the Issuer Name is as same as the one listed on Scroll Ecosystem

**Comment by LaplaceMan** [comment]
> Unable to find the relevant data in the ecosystem list
> 
> Please ensure the Issuer Name is as same as the one listed on Scroll Ecosystem

I have changed the name, please check again, thanks.

**Comment by Holybasil** [comment]
added
