### ISSUE TITLE
[Badge]: Scroll Explorer Badge

### ISSUE THREAD

**Issue by LaplaceMan** [scroll-tech/canvas-badges#67]
### Badge Category

Achievement

### Badge Contract Address

0x7188B352C818f291432CDe8E4B1f0576c188F9e4

### Attester Proxy Address

0x2DCa57F08b8445BD6265b3667D5a420089255b92

### BaseURL of Check/Claim API

https://publicapi.xenobunny.xyz/canvas/lands

### Issuer Name

XenoBunny

### Issuer URL

https://www.xenobunny.xyz/

**Comment by Holybasil** [comment]
Unable to find the relevant data in the ecosystem list

Please ensure the Issuer Name is as same as the one listed on Scroll Ecosystem

**Comment by LaplaceMan** [comment]
> Unable to find the relevant data in the ecosystem list
> 
> Please ensure the Issuer Name is as same as the one listed on Scroll Ecosystem

I have changed the name, please check again, thanks.

**Comment by Holybasil** [comment]
BaseURL should be `https://publicapi.xenobunny.xyz/canvas/lands` 

And please ensure your APIs has been configured for cross-origin access on scroll.io

**Comment by LaplaceMan** [comment]
> BaseURL should be `https://publicapi.xenobunny.xyz/canvas/lands`
> 
> And please ensure your APIs has been configured for cross-origin access on scroll.io

I have made the changes and confirmed them, please check again, thank you.

**Comment by Holybasil** [comment]
added

**Comment by Holybasil** [comment]
![CleanShot 2024-08-02 at 19 42 21@2x](https://github.com/user-attachments/assets/9ea961d6-58a1-471b-9895-7848be565b2d)

please ensure `badgeTokenURI` has been configured for cross-origin access on scroll.io.
