### ISSUE TITLE
[Badge]: Nuri Locker Badge

### ISSUE THREAD

**Issue by keccakdog** [scroll-tech/canvas-badges#79]
### Badge Category

Achievement

### Badge Contract Address

0x1dd225EA9585462FF7cb32b1EE7f9a54a4606b66

### Enable isEligible

Yes

### Issuer Name

Nuri Exchange

### Issuer URL

https://nuri.exchange

**Comment by Holybasil** [comment]
`defaultTokenURI` should return json data

**Comment by keccakdog** [comment]
> `defaultTokenURI` should return json data

fixed, contract address edited in original message : `0x1dd225EA9585462FF7cb32b1EE7f9a54a4606b66`

**Comment by Holybasil** [comment]
please resubmit a badge form, we require `communityURL` now.
