### ISSUE TITLE
[Badge]: Ambient Filloor

### ISSUE THREAD

**Issue by 0xStrobe** [scroll-tech/canvas-badges#8]
### Badge Contract Address

0x21C5E85eBCbd924BA633D4A7A5F2718f25C713D8

### Attester Proxy Address

0xf61B5dAe16948F0f1ed9141634E4647bBaAa4A81

### BaseURL of Check/Claim API

https://ambient-scroll-badge.liquidity.tools/api

### Issuer Name

Ambient Finance

### Issuer URL

https://ambient.finance/

**Comment by Holybasil** [comment]
added
