### ISSUE TITLE
[Badge]: Pencils SOUL Drops

### ISSUE THREAD

**Issue by penpad-dev** [scroll-tech/canvas-badges#80]
### Badge Category

Status

### Badge Contract Address

0x48BD495DD1EcdfBd29be9EAc16242Fd477c45Cd8

### Attester Proxy Address

0x546f7e7257963DcFC3A7885e911e47b76c05BB76

### BaseURL of Check/Claim API

https://pencilsprotocol.io/api/scroll/canvas/badge/pencil

### Issuer Name

Pencils Protocol

### Issuer URL

https://pencilsprotocol.io

**Comment by Holybasil** [comment]
added
