### ISSUE TITLE
[Badge]: Explorer Certificate

### ISSUE THREAD

**Issue by LaplaceMan** [scroll-tech/canvas-badges#87]
### Badge Category

Achievement

### Badge Contract Address

0x4e2F089a2919df2f0264Fd5e8B43b794F3098808

### Attester Proxy Address

0x764Af55daf1cBC7049FAef8e6BC3F626534a7D74

### BaseURL of Check/Claim API

https://publicapi.xenobunny.xyz/canvas/certificate

### Issuer Name

XenoBunny

### Issuer URL

https://www.xenobunny.xyz/

**Comment by Holybasil** [comment]
added

**Comment by LaplaceMan** [comment]
> added

Hi, when the metadata of our badge is updated, how can we get the data displayed on the scroll explore page to refresh as well?

**Comment by Holybasil** [comment]
> > added
> 
> Hi, when the metadata of our badge is updated, how can we get the data displayed on the scroll explore page to refresh as well?

do you mean the metadata returned by `defaultTokenURI`？
If there are any changes to the data, please notify me, and I will make the necessary modifications.

**Comment by LaplaceMan** [comment]
> > > added
> > 
> > 
> > Hi, when the metadata of our badge is updated, how can we get the data displayed on the scroll explore page to refresh as well?
> 
> do you mean the metadata returned by `defaultTokenURI`？ If there are any changes to the data, please notify me, and I will make the necessary modifications.

Yes, we have updated the description of `Scroll Explorer` and `Explorer Certificate` for better clarification, you can get the latest update directly through `defaultTokenURI`. Could you please help to update the content in the scroll badge page, thanks.

**Comment by LaplaceMan** [comment]
> > > added
> > 
> > 
> > Hi, when the metadata of our badge is updated, how can we get the data displayed on the scroll explore page to refresh as well?
> 
> do you mean the metadata returned by `defaultTokenURI`？ If there are any changes to the data, please notify me, and I will make the necessary modifications.

If you see this, please help update the info on both of our badges, thanks!
