### ISSUE TITLE
[Badge]: Fanaticism Scroll Bridger Badge

### ISSUE THREAD

**Issue by gemeniteg** [scroll-tech/canvas-badges#89]
### Badge Category

Achievement

### Badge Contract Address

0xB9CD7EC2A2261AEA5B0251cf2394e5345C95df61

### Attester Proxy Address

0x850C116ea39b49d8714BE4d1dEffDC1009D66C48

### BaseURL of Check/Claim API

https://owlto.finance/nocore_api/v1/campaign/scroll-badge

### Issuer Name

Owlto Finance

**Comment by Holybasil** [comment]
**DefaultTokenURI**
Failed to fetch metadata from https://ipfs.io/ipfs/QmVtdqn6GJu9VQf2pJmPAkusRW5Xmwr4Y6KSU1crQvQ6C2",

**Check API**
Failed to fetch https://owlto.finance/nocore_api/v1/campaign/scroll-badge/check?badge=0x35CBf99F6F4d936b238f6f26b74cB49706d05Eae&recipient=0xe4657139e50E909731de703E1728128197a90447

**Comment by gemeniteg** [comment]
updated

**Comment by Holybasil** [comment]
DefaultTokenURI: https://owlto.finance/files/badge3.json should return a json

**Comment by Holybasil** [comment]
please resubmit a badge form, we require `communityURL` now.
