### ISSUE TITLE
[Badge]: Loyal Scroll Bridger Badge

### ISSUE THREAD

**Issue by gemeniteg** [scroll-tech/canvas-badges#90]
### Badge Category

Achievement

### Badge Contract Address

0x2F942fbCd37693B2f4254fEe6e4cd70508e6235a

### Attester Proxy Address

0x850C116ea39b49d8714BE4d1dEffDC1009D66C48

### BaseURL of Check/Claim API

https://owlto.finance/nocore_api/v1/campaign/scroll-badge

### Issuer Name

Owlto Finance

**Comment by Holybasil** [comment]
[DefaultTokenURI]: Failed to fetch data from https://ipfs.io/ipfs/QmZwVgxdEKEUQLPegwmamJ4pr1Gw8RpbCCYjY8G4frtDxg

**Comment by Holybasil** [comment]
DefaultTokenURI: https://owlto.finance/files/badge2.json should return a json

**Comment by Holybasil** [comment]
please resubmit a badge form, we require `communityURL` now.
