### ISSUE TITLE
[Badge]: Entry Scroll Bridger Badge

### ISSUE THREAD

**Issue by gemeniteg** [scroll-tech/canvas-badges#91]
### Badge Category

Achievement

### Badge Contract Address

0x75ea8fA878314FDb9325a1652898bEfcccf88292

### Attester Proxy Address

0x850C116ea39b49d8714BE4d1dEffDC1009D66C48

### BaseURL of Check/Claim API

https://owlto.finance/nocore_api/v1/campaign/scroll-badge

### Issuer Name

Owlto Finance

**Comment by Holybasil** [comment]
**DefaultTokenURI**
Failed to fetch data from https://ipfs.io/ipfs/QmWojQKvYMQFiqtpdwfB7rJ2Wv9AE41copZFSTWuaVvFUg

**Check API**
Unable to access check API https://owlto.finance/nocore_api/v1/campaign/scroll-badge/check?badge=0x7c61fFE040F7053a6eDFa12A68e521A6E3318e90&recipient=0xe4657139e50E909731de703E1728128197a90447

**Comment by gemeniteg** [comment]
updated

**Comment by Holybasil** [comment]
DefaultTokenURI: Failed to fetch metadata from https://owlto.finance/files/badge1.json

**Comment by Holybasil** [comment]
please resubmit a badge form, we require `communityURL` now.
