### ISSUE TITLE
[Badge]: This badge is designed for users who made cross-chain swap from Blast to Scroll.

### ISSUE THREAD

**Issue by allush** [scroll-tech/canvas-badges#95]
### Badge Category

Achievement

### Badge Contract Address

0xB69cF3247b60F72ba560B3C1e0F53DAF9e9D5201

### Attester Proxy Address

0x7673F45e6E95373BA22651A4f5f594EDEC3006BC

### BaseURL of Check/Claim API

https://api.symbiosis.finance/crosschain/v1/scroll-badge

### Issuer Name

Symbiosis

### Issuer URL

https://symbiosis.finance

**Comment by Holybasil** [comment]
added
