### ISSUE TITLE
[Badge]: This badge is designed for users who made cross-chain swap from Arbitrum One to Scroll.

### ISSUE THREAD

**Issue by allush** [scroll-tech/canvas-badges#97]
### Badge Category

Achievement

### Badge Contract Address

0x35CB802ede5f970AE6d7B8E7b7b82C82Fea273C7

### Attester Proxy Address

0x7673F45e6E95373BA22651A4f5f594EDEC3006BC

### BaseURL of Check/Claim API

https://api.symbiosis.finance/crosschain/v1/scroll-badge

### Issuer Name

Symbiosis

### Issuer URL

https://symbiosis.finance/

**Comment by Holybasil** [comment]
added
