### ISSUE TITLE
[Badge]: This badge is designed for users who made cross-chain swap from Base to Scroll.

### ISSUE THREAD

**Issue by allush** [scroll-tech/canvas-badges#99]
### Badge Category

Status

### Badge Contract Address

0x4445BE64c03154052bd661fD1B0d01FC625Df06E

### Attester Proxy Address

0x7673F45e6E95373BA22651A4f5f594EDEC3006BC

### BaseURL of Check/Claim API

https://api.symbiosis.finance/crosschain/v1/scroll-badge

### Issuer Name

Symbiosis

### Issuer URL

https://symbiosis.finance/

**Comment by Holybasil** [comment]
added
